### ISSUE TITLE
Couldn't restart the countdown

### ISSUE THREAD

**Issue by lazarordzn** [mmobin789/Android-CountDownTimer#1]
Hello.
I implemented your timer in a project and works really good. I'm really happy with the results because it was too easy to implemment.
Well, the question is that i was trying to restart the timer so i will be able to reuse it and call the start method again after finishing the countdown, but it only shows the first message in the Toast (Seconds = 10 Minutes = 0) and then it just don't show the message again.
On the first run shows it all good, but on the second run only shows the first tick.
How is it pretended to do the restart function to work? Or how can i restart the simpleCountDownTimer?

This is my activity code:
`
    

    var min : Int = 0
    var seg : Int = 0
    var cont : Int = 0
    var imagenes : IntArray = IntArray(0)
    val timer : SimpleCountDownTimer = SimpleCountDownTimer(0, 3, 1, this)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }

    fun recibirMensaje(view: View) {
        imagenes = construirAnimacion(etMensaje.text.toString())
        cambiarImagen(imagenes[0])
    }

    fun construirAnimacion(mensaje: String) : IntArray {
        var arrLetras : IntArray = IntArray(mensaje.length)
        var cont : Int = 0
        for (letra in mensaje) {
            arrLetras.set(cont, compararLetra(letra))
            cont++
        }
        return arrLetras
    }

    fun compararLetra(letra: Char) : Int {
        var id : Int = 0
        val let = letra.toUpperCase()
        when (let) {
            'A' -> id = R.drawable.abc_a
            'B' -> id = R.drawable.abc_b
            'C' -> id = R.drawable.abc_c
            'D' -> id = R.drawable.abc_d
            'E' -> id = R.drawable.abc_e
            'F' -> id = R.drawable.abc_f
            'G' -> id = R.drawable.abc_g
            'H' -> id = R.drawable.abc_h
            'I' -> id = R.drawable.abc_i
            'J' -> id = R.drawable.abc_j
            'K' -> id = R.drawable.abc_k
            'L' -> id = R.drawable.abc_l
            'M' -> id = R.drawable.abc_m
            'N' -> id = R.drawable.abc_n
            'Ñ' -> id = R.drawable.abc_nn
            'O' -> id = R.drawable.abc_o
            'P' -> id = R.drawable.abc_p
            'Q' -> id = R.drawable.abc_q
            'R' -> id = R.drawable.abc_r
            'S' -> id = R.drawable.abc_s
            'T' -> id = R.drawable.abc_t
            'U' -> id = R.drawable.abc_u
            'V' -> id = R.drawable.abc_v
            'W' -> id = R.drawable.abc_w
            'X' -> id = R.drawable.abc_x
            'Y' -> id = R.drawable.abc_y
            'Z' -> id = R.drawable.abc_z
        }
        return id
    }

    fun cambiarImagen(imagen : Int) {
        ivAnimacion.visibility = View.VISIBLE
        ivAnimacion.setImageResource(imagen)
        timer.start(false)
    }

    override fun onCountDownActive(time: String?) {
        Toast.makeText(this, "Seconds = " + timer.getSecondsTillCountDown() +
                " Minutes=" + timer.getMinutesTillCountDown(), Toast.LENGTH_SHORT).show();
    }

    override fun onCountDownFinished() {
        cont++
        if (cont < imagenes.size) {
            cambiarImagen(imagenes[cont])
        }
    }

`

I've followed the tutorial on this page [https://android.jlelse.eu/countdown-timer-in-android-941aab8dc976](url)

**Comment by lazarordzn** [comment]
It seems that i could made it to find a fix to this.
I've just reinstantiated the SimpleCountDownTimer instance on the method where i call to the start of the simpleCountDownTimer and it worked.

This is the new code to the function cambiarImagen(imagen: Int) :
`


fun cambiarImagen(imagen : Int) {
        if (imagen != 0) {
            ivAnimacion.visibility = View.VISIBLE
            ivAnimacion.setImageResource(imagen)
        } else {
            ivAnimacion.visibility = View.GONE
        }
        timer = SimpleCountDownTimer(0, 2, 1, listener)
        timer.start(false)
    }





`

**Comment by mmobin789** [comment]
@Altareon98 It look's like you didn't read the tutorial carefully. If you think logically about a restart.
A restart of a process implies whether it's completed/failed or halted for a reason after it was started. So you can achieve a restart by pausing the timer 1st using pause method and then calling the start method again.This will restart it. **You have reinitialized the timer which is a hack and not reliable as it creates another object which is completely redundant**. The following is taken from the same tutorial you read.

> **_Only on completion or paused, the start method can be invoked again with false parameter to restart the timer_** 
>
